Name:           ros-indigo-flexbe-app
Version:        2.1.3
Release:        0%{?dist}
Summary:        ROS flexbe_app package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/flexbe_app
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-actionlib
Requires:       ros-indigo-genpy
Requires:       ros-indigo-rospack
Requires:       ros-indigo-rospy
BuildRequires:  curl
BuildRequires:  libcurl-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-rostest
BuildRequires:  ros-indigo-rosunit

%description
flexbe_app provides a user interface (editor + runtime control) for the FlexBE
behavior engine.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Wed Dec 19 2018 Philipp Schillinger <schillin@kth.se> - 2.1.3-0
- Autogenerated by Bloom

* Tue Dec 18 2018 Philipp Schillinger <schillin@kth.se> - 2.1.2-0
- Autogenerated by Bloom

* Sat Dec 01 2018 Philipp Schillinger <schillin@kth.se> - 2.1.0-0
- Autogenerated by Bloom

